### ISSUE TITLE
🚨 Potential Security Vulnerability - huntr.dev

### ISSUE THREAD

**Issue by huntr-helper** [rostwolke/node-wireguard-wrapper#3]
#### ⚠️ Potential Vulnerability in node-wireguard-wrapper

👋 Hello, @rostwolke - @hzgue has disclosed a potential vulnerability in your repository. To validate or invalidate this potential vulnerability, please visit https://huntr.dev/bounties/1-npm-wireguard-wrapper and join our community in helping secure open-source code.

---

#### ☎️ Need further support?

Come and join us on our [Discord](https://huntr.dev/discord) and a member of our team will be happy to help! 🤗

cc - @JamieSlome

**Comment by rostwolke** [comment]
This bug has been fixed quite a while ago. Also it was originally posted by d3lla on hackerone and fixed by thackeraaron.
